/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatMessageItem: typeof import('./src/components/ChatMessageItem/components/ChatMessageItem.vue')['default']
    ChatMessageItemStrategy: typeof import('./src/components/ChatMessageItem/ChatMessageItemStrategy.vue')['default']
    ChatSystemItem: typeof import('./src/components/ChatMessageItem/components/ChatSystemItem.vue')['default']
    DraggableResize: typeof import("./src/components/DraggableResize/DraggableResize.vue")["default"]
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"]
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"]
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"]
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"]
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"]
    LoginDialog: typeof import('./src/components/LoginDialog/LoginDialog.vue')['default']
    MessageItem: typeof import("./src/components/ChatMessageItem/MessageItem.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContainer: typeof import("./src/components/ScrollContainer.vue")["default"]
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"]
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"]
  }
}
