/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlackCollapse: typeof import('./src/components/BlackCollapse/BlackCollapse.vue')['default']
    BlackCollapseItem: typeof import('./src/components/BlackCollapse/BlackCollapseItem.vue')['default']
    BlackEmojis: typeof import('./src/components/EmojiList/BlackEmojis.vue')['default']
    BlackSortedList: typeof import('./src/components/BlackSortedList/BlackSortedList.vue')['default']
    BlackTabs: typeof import('./src/components/BlackTabs/BlackTabs.vue')['default']
    ChatEmoji: typeof import('./src/components/ChatEmoji/ChatEmoji.vue')['default']
    ChatMessageItem: typeof import('./src/components/ChatMessageItem/components/ChatMessageItem.vue')['default']
    ChatMessageItemStrategy: typeof import('./src/components/ChatMessageItem/ChatMessageItemStrategy.vue')['default']
    ChatSystemItem: typeof import('./src/components/ChatMessageItem/components/ChatSystemItem.vue')['default']
    DraggableResize: typeof import("./src/components/DraggableResize/DraggableResize.vue")["default"]
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EmojiList: typeof import('./src/components/EmojiList/EmojiList.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"]
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"]
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"]
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"]
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"]
    LoginDialog: typeof import('./src/components/LoginDialog/LoginDialog.vue')['default']
    MessageItem: typeof import("./src/components/ChatMessageItem/MessageItem.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContainer: typeof import("./src/components/ScrollContainer.vue")["default"]
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"]
    UserInfoDialog: typeof import('./src/components/UserInfoDialog/UserInfoDialog.vue')['default']
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"]
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
